spring.profiles.active: git

management:
  endpoints.web.exposure.include: "*"
  endpoint.shutdown.enabled: true

---
spring:
  config.activate.on-profile: git
  cloud.config.server.git:
          uri: https://github.com/springone-tour-2021/color-app
          search-paths: config-files/

---
spring:
  config.activate.on-profile: native
  cloud.config.server.native:
          searchLocations: file://${user.home}/color-app/config-files
#          searchLocations: file://${user.home}/workspace/springone-tour-2021/color-app/config-files
